# -*- coding: utf-8 -*-
"""Copy of MultiLinear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BmxToBCKLB1bQem2mZS1QI8DHh-L_lce
"""

import numpy as np
import pandas as pd
from sklearn import linear_model

df = pd.read_csv("/content/drive/MyDrive/car_sales_data.csv")
df

import pandas as pd
from sklearn import linear_model

df = pd.read_csv("/content/drive/MyDrive/Car_Sales.csv")

# Drop rows where 'Price' is NaN
df.dropna(subset=['Price'], inplace=True)

lr = linear_model.LinearRegression()
lr.fit(df[['Engine size','Year of manufacture','Mileage']],df['Price'])

# This will give COD (Coeffiecient of determination)
lr.score(df[['Engine size','Year of manufacture','Mileage']],df['Price'])



# here we give values of independent variables and predic answer as Y
lr.predict([[4,2016,57850]])

lr.coef_

lr.intercept_

# This is formula in coeffienet value will multiply with values and intercept will add
price = 8.93379634e+03 * 4 +  9.88706309e+02 * 2016 + -3.79058734e-02 * 57850 -1979321.008206213

print(price)

# This code is for saving file in google drive link and load it means write
import pickle
from sklearn import linear_model
lr = linear_model.LinearRegression()
with open('/content/drive/MyDrive/car_sales_model.pickle','wb') as f:
  pickle.dump(lr,f)

# This code is for saving file in google drive link and load it means read
import pickle
from sklearn import linear_model
lr = linear_model.LinearRegression()
lr.fit(df[['Engine size','Year of manufacture','Mileage']],df['Price'])
with open('/content/drive/MyDrive/car_sales_model.pickle','rb') as f:
 lr2 = pickle.load(f)

lr2.fit(df[['Engine size','Year of manufacture','Mileage']],df['Price'])
lr2.predict([[4,2016,57850]])

# if you load big files with more numpy arrays you need to import joblib
import joblib
joblib.dump(lr,'/content/drive/MyDrive/car_sales_model.joblib')

# here we load in with joblib and create new liner regression and then predict values
lr3 = joblib.load('/content/drive/MyDrive/car_sales_model.joblib')

# Here we split data for test & training purpose
x = df[['Year of manufacture','Mileage']]
y = df['Price']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
len(y_test)

# We run the model and check the result of trained model with predicted model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

lr.predict(x_test)

y_test

# Here trained model compared with the actual model
lr.score(x_test,y_test)

lr3.predict([[4,2016,57850]])