# -*- coding: utf-8 -*-
"""Multiclass Classification Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tr5xDlyKLiJmf9YbDoHvmiIUaipWFbQV
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
df = pd.read_csv('/content/drive/MyDrive/IRIS.csv')
df.head()

# Encode Categorical Columns
# ======================================
label_encoder = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = label_encoder.fit_transform(df[col])

# ======================================

# Step 6: Train-Test Split
# ======================================
# Define features (X) and target (y)
X = df.drop('species', axis=1)
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)



# Step 7: Train Model
# ======================================
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

# Step 8: Make Predictions
# ======================================
y_pred = model.predict(X_test)

# Step 9: Evaluate Model
# ======================================
print("Accuracy:", accuracy_score(y_test, y_pred))

# Classification Report
print("\nClassification Report")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))