# -*- coding: utf-8 -*-
"""Simple Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rPLi0HpYZbswKaNn44lMe0fHXZipoaR0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
df = pd.read_csv('/content/drive/MyDrive/simplelinearregression.csv')
df

plt.scatter(df.Age,df.Premium,color='red',marker='*')
plt.xlabel('Age',color = "Blue")
plt.ylabel('Premium', color = "Blue")
plt.title('Age vs Premium', color = "Red")
plt.show()
plt



lr = linear_model.LinearRegression()
lr.fit(df[["Age"]],df.Premium)

lr.predict([[27]])

lr.intercept_

lr.score(df[["Age"]],df.Premium)

lr.coef_

Predicted = 1172.94520548 * 27 -10114.726027397272
print(Predicted)

plt.scatter(df.Age,df.Premium,color='red',marker='+')
plt.xlabel('Age',color = "Red")
plt.ylabel('Premium', color = "Red")
plt.title('Age vs Premium', color = "Red")
plt.plot(df.Age,lr.predict(df[["Age"]]),color='blue')

plt